services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: myServer
    restart: always
    ports:
      - '80:3005'
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MY_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MY_PASSWORD}
      MONGO_INITDB_DATABASE: ${MY_DATABASE}
    container_name: myMongo
    restart: always
    ports:
      - '27017:27017'

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
